# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1296, 745)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_inicial = QtWidgets.QWidget()
        self.page_inicial.setObjectName("page_inicial")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_inicial)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridGroupBox_14 = QtWidgets.QGroupBox(self.page_inicial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridGroupBox_14.sizePolicy().hasHeightForWidth())
        self.gridGroupBox_14.setSizePolicy(sizePolicy)
        self.gridGroupBox_14.setStyleSheet("QGroupBox {border: none;\n"
"            }")
        self.gridGroupBox_14.setObjectName("gridGroupBox_14")
        self.gridLayout_55 = QtWidgets.QGridLayout(self.gridGroupBox_14)
        self.gridLayout_55.setObjectName("gridLayout_55")
        self.line_3 = QtWidgets.QFrame(self.gridGroupBox_14)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_55.addWidget(self.line_3, 0, 0, 1, 3)
        self.label_72 = QtWidgets.QLabel(self.gridGroupBox_14)
        self.label_72.setMinimumSize(QtCore.QSize(0, 0))
        self.label_72.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.gridLayout_55.addWidget(self.label_72, 2, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gridGroupBox_14)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_55.addWidget(self.line_4, 3, 0, 1, 3)
        self.gridLayout_2.addWidget(self.gridGroupBox_14, 5, 0, 1, 3)
        self.gridGroupBox_login = QtWidgets.QGroupBox(self.page_inicial)
        self.gridGroupBox_login.setStyleSheet("QGroupBox {\n"
"                border: 1px solid #bababa; /* borda cinza */\n"
"                border-radius: 10px; /* borda arredondada */\n"
"                background-color: rgb(255, 255, 255);\n"
"            }\n"
"            QGroupBox::title {\n"
"                subcontrol-origin: margin;\n"
"                subcontrol-position: top center;\n"
"                padding: 0 3px;\n"
"            }\n"
"")
        self.gridGroupBox_login.setAlignment(QtCore.Qt.AlignCenter)
        self.gridGroupBox_login.setObjectName("gridGroupBox_login")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridGroupBox_login)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_17 = QtWidgets.QLabel(self.gridGroupBox_login)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_12.addWidget(self.label_17, 1, 1, 1, 3)
        self.btn_autenticar = QtWidgets.QPushButton(self.gridGroupBox_login)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_autenticar.setFont(font)
        self.btn_autenticar.setStyleSheet("QPushButton {\n"
"                border: 2px solid #004a99; /* borda azul */\n"
"                border-radius: 5px; /* bordas mais quadradas */\n"
"                color: #004a99; /* fonte azul */\n"
"                padding:3px 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #004a99; /* hover azul */\n"
"                color: #ffffff; /* fonte branca */\n"
"            }")
        self.btn_autenticar.setObjectName("btn_autenticar")
        self.gridLayout_12.addWidget(self.btn_autenticar, 6, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem, 5, 2, 1, 1)
        self.ln_usuarioLogin = QtWidgets.QLineEdit(self.gridGroupBox_login)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ln_usuarioLogin.setFont(font)
        self.ln_usuarioLogin.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"                border-radius: 5px; \n"
"color: rgb(0, 74, 153);\n"
"padding: 2px 3px")
        self.ln_usuarioLogin.setObjectName("ln_usuarioLogin")
        self.gridLayout_12.addWidget(self.ln_usuarioLogin, 3, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridGroupBox_login)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_18.setObjectName("label_18")
        self.gridLayout_12.addWidget(self.label_18, 4, 1, 1, 1)
        self.ln_senhaLogin = QtWidgets.QLineEdit(self.gridGroupBox_login)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ln_senhaLogin.setFont(font)
        self.ln_senhaLogin.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"                border-radius: 5px; \n"
"color: rgb(0, 74, 153);\n"
"padding: 2px 3px")
        self.ln_senhaLogin.setText("")
        self.ln_senhaLogin.setObjectName("ln_senhaLogin")
        self.gridLayout_12.addWidget(self.ln_senhaLogin, 4, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridGroupBox_login)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_11.setObjectName("label_11")
        self.gridLayout_12.addWidget(self.label_11, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem1, 2, 1, 1, 1)
        self.show_password_button = QtWidgets.QPushButton(self.gridGroupBox_login)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.show_password_button.setFont(font)
        self.show_password_button.setText("")
        self.show_password_button.setObjectName("show_password_button")
        self.gridLayout_12.addWidget(self.show_password_button, 4, 3, 1, 1)
        self.gridLayout_2.addWidget(self.gridGroupBox_login, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_inicial)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 4, 1, 1, 1)
        self.gridGroupBox_logo = QtWidgets.QGroupBox(self.page_inicial)
        self.gridGroupBox_logo.setMinimumSize(QtCore.QSize(400, 200))
        self.gridGroupBox_logo.setMaximumSize(QtCore.QSize(400, 200))
        self.gridGroupBox_logo.setStyleSheet("border:  None")
        self.gridGroupBox_logo.setObjectName("gridGroupBox_logo")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.gridGroupBox_logo)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.logo = QtWidgets.QLabel(self.gridGroupBox_logo)
        self.logo.setStyleSheet("")
        self.logo.setText("")
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.gridLayout_25.addWidget(self.logo, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gridGroupBox_logo, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_inicial)
        self.page_cadastro = QtWidgets.QWidget()
        self.page_cadastro.setObjectName("page_cadastro")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.page_cadastro)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.scrollArea = QtWidgets.QScrollArea(self.page_cadastro)
        self.scrollArea.setStyleSheet("QScrollArea { border: none; }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1260, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem6, 3, 1, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 3, 0, 1, 1)
        self.ln_marca = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ln_marca.setFont(font)
        self.ln_marca.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"border-radius: 5px; \n"
"padding: 2 5px;\n"
"")
        self.ln_marca.setText("")
        self.ln_marca.setObjectName("ln_marca")
        self.gridLayout_9.addWidget(self.ln_marca, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 0, 0, 1, 1)
        self.ln_cd = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ln_cd.setFont(font)
        self.ln_cd.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"border-radius: 5px; \n"
"padding: 2 5px;\n"
"")
        self.ln_cd.setText("")
        self.ln_cd.setObjectName("ln_cd")
        self.gridLayout_9.addWidget(self.ln_cd, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 1, 0, 1, 1)
        self.ln_cat = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ln_cat.setFont(font)
        self.ln_cat.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"border-radius: 5px; \n"
"padding: 2 5px;\n"
"")
        self.ln_cat.setText("")
        self.ln_cat.setObjectName("ln_cat")
        self.gridLayout_9.addWidget(self.ln_cat, 3, 1, 1, 1)
        self.ln_custo = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ln_custo.setFont(font)
        self.ln_custo.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"border-radius: 5px; \n"
"padding: 2 5px;\n"
"")
        self.ln_custo.setText("")
        self.ln_custo.setObjectName("ln_custo")
        self.gridLayout_9.addWidget(self.ln_custo, 5, 1, 1, 1)
        self.ln_tipo = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ln_tipo.setFont(font)
        self.ln_tipo.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"border-radius: 5px; \n"
"padding: 2 5px;\n"
"")
        self.ln_tipo.setText("")
        self.ln_tipo.setObjectName("ln_tipo")
        self.gridLayout_9.addWidget(self.ln_tipo, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_13.setObjectName("label_13")
        self.gridLayout_9.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_15.setObjectName("label_15")
        self.gridLayout_9.addWidget(self.label_15, 4, 0, 1, 1)
        self.ln_preco = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ln_preco.setFont(font)
        self.ln_preco.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"border-radius: 5px; \n"
"padding: 2 5px;\n"
"")
        self.ln_preco.setText("")
        self.ln_preco.setObjectName("ln_preco")
        self.gridLayout_9.addWidget(self.ln_preco, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 6, 0, 1, 1)
        self.ln_obs = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ln_obs.setFont(font)
        self.ln_obs.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"border-radius: 5px; \n"
"padding: 2 5px;\n"
"")
        self.ln_obs.setText("")
        self.ln_obs.setObjectName("ln_obs")
        self.gridLayout_9.addWidget(self.ln_obs, 6, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_9, 2, 0, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem7, 6, 1, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(0, 74, 153);\n"
"color: rgb(255, 255, 255);\n"
"padding: 5px 5px")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_8, 0, 0, 1, 3)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem8 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem8, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_15, 5, 0, 1, 1)
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.btn_enviar = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_enviar.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_enviar.setStyleSheet("QPushButton {\n"
"                border: 2px solid #004a99; /* borda azul */\n"
"                border-radius: 10px; /* bordas mais quadradas */\n"
"                color: #004a99; /* fonte azul */\n"
"                padding:3px 10px;\n"
"            }\n"
"QPushButton:hover {\n"
"                background-color: #004a99; /* hover azul */\n"
"                color: #ffffff; /* fonte branca */\n"
"            }")
        self.btn_enviar.setObjectName("btn_enviar")
        self.gridLayout_33.addWidget(self.btn_enviar, 0, 1, 1, 1)
        self.btn_limpar = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_limpar.sizePolicy().hasHeightForWidth())
        self.btn_limpar.setSizePolicy(sizePolicy)
        self.btn_limpar.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_limpar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_limpar.setStyleSheet("QPushButton {\n"
"                border: 2px solid #b22222; /* borda azul */\n"
"                border-radius: 10px; /* bordas mais quadradas */\n"
"                color: #b22222; /* fonte azul */\n"
"                padding:3px 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #b22222; /* hover azul */\n"
"                color: #ffffff; /* fonte branca */\n"
"            }")
        self.btn_limpar.setObjectName("btn_limpar")
        self.gridLayout_33.addWidget(self.btn_limpar, 0, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_33.addItem(spacerItem9, 0, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_33.addItem(spacerItem10, 0, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_33, 4, 0, 1, 3)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem11, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_17.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_cadastro)
        self.page_consulta = QtWidgets.QWidget()
        self.page_consulta.setObjectName("page_consulta")
        self.gridLayout_56 = QtWidgets.QGridLayout(self.page_consulta)
        self.gridLayout_56.setObjectName("gridLayout_56")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.page_consulta)
        self.scrollArea_4.setStyleSheet("QScrollArea { border: none; }")
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 1260, 600))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.tableView_consulta = QtWidgets.QTableView(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableView_consulta.setFont(font)
        self.tableView_consulta.setStyleSheet("QTableView {\n"
"                border: 2px solid #bababa; /* Cor da borda da tabela */\n"
"                border-radius: 5px; /* Cantos arredondados da tabela */\n"
"                selection-background-color: #004a99; /* Cor de fundo da seleção */\n"
"                gridline-color: #004a99; /* Cor das linhas de grade */\n"
"            }\n"
"            QTableView::item {\n"
"                padding: 5px; /* Espaçamento interno das células */\n"
"                color: #000000; /* Cor do texto */\n"
"            }\n"
"            QHeaderView::section {\n"
"                background-color: #bababa; /* Cor de fundo dos cabeçalhos */\n"
"                color: #000000; /* Cor do texto dos cabeçalhos */\n"
"                padding: 5px; /* Espaçamento interno dos cabeçalhos */\n"
"            }")
        self.tableView_consulta.setObjectName("tableView_consulta")
        self.gridLayout_38.addWidget(self.tableView_consulta, 4, 0, 1, 2)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_38.addItem(spacerItem12, 3, 0, 1, 1)
        self.gridLayout_51 = QtWidgets.QGridLayout()
        self.gridLayout_51.setObjectName("gridLayout_51")
        self.label_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setStyleSheet("background-color: rgb(0, 74, 153);\n"
"color: rgb(255, 255, 255);\n"
"padding: 5px 5px")
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.gridLayout_51.addWidget(self.label_62, 0, 0, 1, 1)
        self.gridLayout_38.addLayout(self.gridLayout_51, 0, 0, 1, 2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_38.addItem(spacerItem13, 5, 0, 1, 1)
        self.gridLayout_49 = QtWidgets.QGridLayout()
        self.gridLayout_49.setObjectName("gridLayout_49")
        self.ln_cons_categoria = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_cons_categoria.sizePolicy().hasHeightForWidth())
        self.ln_cons_categoria.setSizePolicy(sizePolicy)
        self.ln_cons_categoria.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ln_cons_categoria.setFont(font)
        self.ln_cons_categoria.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"border-radius: 5px; \n"
"padding: 2 5px;\n"
"")
        self.ln_cons_categoria.setText("")
        self.ln_cons_categoria.setObjectName("ln_cons_categoria")
        self.gridLayout_49.addWidget(self.ln_cons_categoria, 0, 7, 1, 1)
        self.ln_cons_tipo = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_cons_tipo.sizePolicy().hasHeightForWidth())
        self.ln_cons_tipo.setSizePolicy(sizePolicy)
        self.ln_cons_tipo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ln_cons_tipo.setFont(font)
        self.ln_cons_tipo.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"border-radius: 5px; \n"
"padding: 2 5px;\n"
"")
        self.ln_cons_tipo.setText("")
        self.ln_cons_tipo.setObjectName("ln_cons_tipo")
        self.gridLayout_49.addWidget(self.ln_cons_tipo, 0, 5, 1, 1)
        self.ln_cons_cd = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_cons_cd.sizePolicy().hasHeightForWidth())
        self.ln_cons_cd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ln_cons_cd.setFont(font)
        self.ln_cons_cd.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"border-radius: 5px; \n"
"padding: 2 5px;\n"
"")
        self.ln_cons_cd.setText("")
        self.ln_cons_cd.setObjectName("ln_cons_cd")
        self.gridLayout_49.addWidget(self.ln_cons_cd, 0, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_59.setObjectName("label_59")
        self.gridLayout_49.addWidget(self.label_59, 0, 4, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_61.setObjectName("label_61")
        self.gridLayout_49.addWidget(self.label_61, 0, 2, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_60.setObjectName("label_60")
        self.gridLayout_49.addWidget(self.label_60, 0, 0, 1, 1)
        self.btn_cons_procurar = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.btn_cons_procurar.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_cons_procurar.setStyleSheet("QPushButton {\n"
"                border: 2px solid #004a99; /* borda azul */\n"
"                border-radius: 5px; /* bordas mais quadradas */\n"
"                color: #004a99; /* fonte azul */\n"
"                padding:3px 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #004a99; /* hover azul */\n"
"                color: #ffffff; /* fonte branca */\n"
"            }")
        self.btn_cons_procurar.setObjectName("btn_cons_procurar")
        self.gridLayout_49.addWidget(self.btn_cons_procurar, 0, 9, 1, 1)
        self.ln_cons_marca = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_cons_marca.sizePolicy().hasHeightForWidth())
        self.ln_cons_marca.setSizePolicy(sizePolicy)
        self.ln_cons_marca.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ln_cons_marca.setFont(font)
        self.ln_cons_marca.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"border-radius: 5px; \n"
"padding: 2 5px;\n"
"")
        self.ln_cons_marca.setText("")
        self.ln_cons_marca.setObjectName("ln_cons_marca")
        self.gridLayout_49.addWidget(self.ln_cons_marca, 0, 3, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_54.setObjectName("label_54")
        self.gridLayout_49.addWidget(self.label_54, 0, 6, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_49.addItem(spacerItem14, 0, 8, 1, 1)
        self.gridLayout_38.addLayout(self.gridLayout_49, 2, 0, 1, 2)
        spacerItem15 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_38.addItem(spacerItem15, 1, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_56.addWidget(self.scrollArea_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_consulta)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.gridGroupBox_navegacao = QtWidgets.QGroupBox(self.centralwidget)
        self.gridGroupBox_navegacao.setStyleSheet("QGroupBox {border: none;\n"
"            }")
        self.gridGroupBox_navegacao.setObjectName("gridGroupBox_navegacao")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridGroupBox_navegacao)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.line = QtWidgets.QFrame(self.gridGroupBox_navegacao)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 2, 0, 1, 5)
        self.line_2 = QtWidgets.QFrame(self.gridGroupBox_navegacao)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_6.addWidget(self.line_2, 0, 0, 1, 5)
        self.btn_home = QtWidgets.QPushButton(self.gridGroupBox_navegacao)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_home.setFont(font)
        self.btn_home.setStyleSheet("QPushButton {\n"
"                border: 2px solid #004a99; /* borda azul */\n"
"                border-radius: 5px; /* bordas mais quadradas */\n"
"                color: #004a99; /* fonte azul */\n"
"                padding:3px 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #004a99; /* hover azul */\n"
"                color: #ffffff; /* fonte branca */\n"
"            }")
        self.btn_home.setObjectName("btn_home")
        self.gridLayout_6.addWidget(self.btn_home, 1, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem16, 1, 3, 1, 1)
        self.btn_consulta = QtWidgets.QPushButton(self.gridGroupBox_navegacao)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_consulta.setFont(font)
        self.btn_consulta.setStyleSheet("QPushButton {\n"
"                border: 2px solid #004a99; /* borda azul */\n"
"                border-radius: 5px; /* bordas mais quadradas */\n"
"                color: #004a99; /* fonte azul */\n"
"                padding:3px 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #004a99; /* hover azul */\n"
"                color: #ffffff; /* fonte branca */\n"
"            }")
        self.btn_consulta.setObjectName("btn_consulta")
        self.gridLayout_6.addWidget(self.btn_consulta, 1, 2, 1, 1)
        self.btn_cadastrar = QtWidgets.QPushButton(self.gridGroupBox_navegacao)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_cadastrar.setFont(font)
        self.btn_cadastrar.setStyleSheet("QPushButton {\n"
"                border: 2px solid #004a99; /* borda azul */\n"
"                border-radius: 5px; /* bordas mais quadradas */\n"
"                color: #004a99; /* fonte azul */\n"
"                padding:3px 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #004a99; /* hover azul */\n"
"                color: #ffffff; /* fonte branca */\n"
"            }")
        self.btn_cadastrar.setObjectName("btn_cadastrar")
        self.gridLayout_6.addWidget(self.btn_cadastrar, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.gridGroupBox_navegacao, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1296, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Controle de Padrões"))
        self.label_72.setText(_translate("MainWindow", "© 2024 Hashtag Treinamentos. Todos os Direitos Reservados"))
        self.label_17.setText(_translate("MainWindow", "Faça seu Login para acessar"))
        self.btn_autenticar.setText(_translate("MainWindow", "Logar"))
        self.label_18.setText(_translate("MainWindow", "Senha:"))
        self.label_11.setText(_translate("MainWindow", "E-mail:"))
        self.label_10.setText(_translate("MainWindow", "Sistema Python PowerUp"))
        self.label_8.setText(_translate("MainWindow", "Categoria do Produto:"))
        self.label_2.setText(_translate("MainWindow", "Código do Produto:"))
        self.label_3.setText(_translate("MainWindow", "Marca do Produto:"))
        self.label_13.setText(_translate("MainWindow", "Custo do Produto:"))
        self.label_15.setText(_translate("MainWindow", "Preço Unitário do Produto:"))
        self.label_9.setText(_translate("MainWindow", "Tipo do Produto:"))
        self.label_4.setText(_translate("MainWindow", "OBS:"))
        self.label_12.setText(_translate("MainWindow", "Formulário de Cadastro de Produtos"))
        self.btn_enviar.setText(_translate("MainWindow", "Enviar"))
        self.btn_limpar.setText(_translate("MainWindow", "Limpar"))
        self.label_62.setText(_translate("MainWindow", "Produtos Cadastrados"))
        self.label_59.setText(_translate("MainWindow", "Tipo:"))
        self.label_61.setText(_translate("MainWindow", "Marca:"))
        self.label_60.setText(_translate("MainWindow", "Código:"))
        self.btn_cons_procurar.setText(_translate("MainWindow", "Procurar"))
        self.label_54.setText(_translate("MainWindow", "Categoria:"))
        self.btn_home.setText(_translate("MainWindow", "Início"))
        self.btn_consulta.setText(_translate("MainWindow", "Consulta"))
        self.btn_cadastrar.setText(_translate("MainWindow", "Cadastro"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
